#!/usr/bin/env sh

####################################################################################
#   Run this file from the root of the repository to build and run a PWA container #
####################################################################################
CONFIG_ENV_FILE=./docker/.env.docker.dev
STATUS=0

# accepts -e <envfile_path> to set a separate environment variable file configuration
while getopts ":e" opt; do
  case ${opt} in
    e )
      # validate that the file path passed is valid
      if [ -f $2 ]; then
        CONFIG_ENV_FILE="$2"
        echo "Configuration using environment variables from: $2"
      else
        echo -e "The env file you provided does not exist at this path: $2\nPlease provide the relative path to your environment file.\nExample: $CONFIG_ENV_FILE"
        exit 1
      fi
      ;;
  esac
done

main () {
  env_setup
  create_certificate
  # If cert setup failed then don't start docker
  if [ "$STATUS" = "0" ]; then
    start_docker
  else
    message "An error occurred during setup."
    exit 1
  fi
}

env_setup () {
  message "Adding env vars from $CONFIG_ENV_FILE for docker setup."
  cat $CONFIG_ENV_FILE
  . $CONFIG_ENV_FILE
}

create_certificate () {
  message "Creating SSL/TLS certificate"
  # make docker/certs folder if one does not already exist
  [ -d ./docker/certs ] || mkdir ./docker/certs
  # install devcert dependency
  cd ./docker && yarn install && cd -
  node ./docker/makeHostAndCert "$DEV_SERVER_HOST" || STATUS=$?
}

start_docker () {
  message "Building PWA image"
  BUILD_STATUS=0
  docker-compose --env-file $CONFIG_ENV_FILE build || BUILD_STATUS=$?

  if [ "$BUILD_STATUS" = "0" ]; then
    message "Starting Docker network and containers"
    docker-compose --env-file $CONFIG_ENV_FILE up
  else
    message "Build failed. See output for details."
  fi
}


message () {
  echo ""
  echo "==========================================================================="
  echo ""
  echo -e "        " "$1"
  echo ""
  echo "==========================================================================="
  echo ""
}

main
