name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        uses: cypress-io/github-action@v1
        with:
          # just perform install
          runTests: false
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          build: yarn build
          start: yarn start
          working-directory: e2e
          env: port=28080
        env:
          MAGENTO_BACKEND_URL: ${{ secrets.MAGENTO_BACKEND_URL }}
          CHECKOUT_BRAINTREE_TOKEN: ${{ secrets.CHECKOUT_BRAINTREE_TOKEN }}
          MAGENTO_BACKEND_EDITION: CE
          IMAGE_OPTIMIZING_ORIGIN: onboard
          PORT: 28080
          NODE_ENV: production
