name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        uses: cypress-io/github-action@v1
        with:
          # just perform install
          runTests: false
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          build: npm install -g devcert-cli && && devcert generate github.pwadev.test && yarn buildpack create-custom-origin .
          start: yarn watch --info-verbosity none
          working-directory: e2e
          env: host=https://github.pwadev.test,port=28080
        env:
          MAGENTO_BACKEND_URL: ${{ secrets.MAGENTO_BACKEND_URL }}
          CHECKOUT_BRAINTREE_TOKEN: ${{ secrets.CHECKOUT_BRAINTREE_TOKEN }}
          MAGENTO_BACKEND_EDITION: CE
          IMAGE_OPTIMIZING_ORIGIN: onboard
          CUSTOM_ORIGIN_EXACT_DOMAIN: pwadev.test
          CUSTOM_ORIGIN_SUBDOMAIN: github
          DEV_SERVER_PORT: 28080
          CUSTOM_ORIGIN_ADD_UNIQUE_HASH: false
          NODE_ENV: development
          CYPRESS_BASE_URL: https://github.pwadev.test:28080
