name: Package Upstream
on:
  push:
    branches:
      - releases

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        release: 
          - "v7.0.0"
          - "v8.0.0"

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
      name: Checkout files
    - run: .github/build-and-tag-upstream.sh ${{ matrix.release }}
    - name: Push Changes
      run: |
              git config --global user.name ${{ github.repository_owner }}
              git config --global user.email ${{ github.repository_owner }}'@users.noreply.github.com'
              if [ -n "$(git status --porcelain)" ]; then
                git add .
                git commit --message "Created release ${{ matrix.release }}"
                git tag ${{ matrix.release }}
                git push origin releases 
                git push origin releases --tags
              fi